### ISSUE TITLE
Failure on github.com/fabiosangregorio/telereddit

### ISSUE THREAD

**Issue by mristin** [Parquery/pyicontract-lint#21]
*(This is a fork from the issue #15.)*

@fabiosangregorio wrote:

> Unfortunately I'm still not able to run pyicontract-lint due to another error. I'm trying to run it on this repo.
> Here's the stacktrace:

```
> pyicontract-lint telereddit
Traceback (most recent call last):
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python38-32\Scripts\pyicontract-lint.exe\__main__.py", line 7, in <module>
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract_lint\main.py", line 66, in main 
    return _main(args=args, stream=sys.stdout)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract_lint\main.py", line 48, in _main
    errors = icontract_lint.check_paths(paths=args.paths)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract\_checkers.py", line 396, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract_lint\__init__.py", line 545, in 
check_paths
    errs.extend(check_recursively(path=pth))
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract\_checkers.py", line 396, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract_lint\__init__.py", line 525, in 
check_recursively
    errs.extend(check_file(pth))
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract\_checkers.py", line 396, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\icontract_lint\__init__.py", line 494, in 
check_file
    tree = astroid.parse(code=text, module_name=modname, path=path.as_posix())
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\builder.py", line 279, in parse   
    return builder.string_build(code, modname=module_name, path=path)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\builder.py", line 144, in string_build
    return self._post_build(module, "utf-8")
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\builder.py", line 162, in _post_build
    module = self._manager.visit_transforms(module)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\manager.py", line 75, in visit_transforms
    return self._transform.visit(node)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\transforms.py", line 89, in visit 
    module.body = [self._visit(child) for child in module.body]
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\transforms.py", line 89, in <listcomp>
    module.body = [self._visit(child) for child in module.body]
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\transforms.py", line 57, in _visit
    return self._transform(node)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\transforms.py", line 40, in _transform
    ret = transform_func(node)
  File "c:\users\fabio\appdata\local\programs\python\python38-32\lib\site-packages\astroid\brain\brain_namedtuple_enum.py", line 350, in infer_enum_class
    name=target.name,
AttributeError: 'Starred' object has no attribute 'name'
```

**Comment by mristin** [comment]
Hi @fabiosangregorio ,
The file `models/content_type.py` seems to cause trouble:
```
"""Module for ContentType class."""

from enum import Enum


class ContentType(Enum):
    """Enumerable to represent different `telereddit.models.post.Post` types."""

    TEXT, PHOTO, VIDEO, GIF, YOUTUBE, *_ = range(20)
```

The astroid seems confused with the asterisk (`Starred`). I opened an issue on their repository (https://github.com/PyCQA/astroid/issues/835).

**Comment by fabiosangregorio** [comment]
Wow thank you so much for the insight @mristin! I wouldn't have been able to find this problem without you.
I can confirm that resolving this problem pyicontract-lint works wonder on my repository. 
Thank you again for your time!

**Comment by mristin** [comment]
Hi @fabiosangregorio ,
I'll close the issue for now. The PR #24 gives informative messages now, so it should be easier to trace the problem(s) in the future. I'll wait a bit till we collect a couple of features for a patch release.
